// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb3YmC9T4JsUVM3HOZoft8WXAt0Xv9Hv4',
    appId: '1:297038881264:web:471b8d1a2ac0a1c33efd35',
    messagingSenderId: '297038881264',
    projectId: 'sneaker-st',
    authDomain: 'sneaker-st.firebaseapp.com',
    storageBucket: 'sneaker-st.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArssrPKRbnUB1vYhpSic8fdQgmkLwtoMs',
    appId: '1:297038881264:android:d09931c0c58669bd3efd35',
    messagingSenderId: '297038881264',
    projectId: 'sneaker-st',
    storageBucket: 'sneaker-st.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx-9VqpzYWmFpcCUyk0VUxKgrHH8leL1g',
    appId: '1:297038881264:ios:7cb12b830e440ebd3efd35',
    messagingSenderId: '297038881264',
    projectId: 'sneaker-st',
    storageBucket: 'sneaker-st.appspot.com',
    iosClientId: '297038881264-on2rg7untkd3o0mhh9n0tm53ilo6ncd5.apps.googleusercontent.com',
    iosBundleId: 'com.example.clgProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx-9VqpzYWmFpcCUyk0VUxKgrHH8leL1g',
    appId: '1:297038881264:ios:fddb06970b2679d73efd35',
    messagingSenderId: '297038881264',
    projectId: 'sneaker-st',
    storageBucket: 'sneaker-st.appspot.com',
    iosClientId: '297038881264-403hbhv670e7lff6l2sk02i9p2hk5nt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.clgProject.RunnerTests',
  );
}
